//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: schemes.proto
namespace schemes
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Monster")]
  public partial class Monster : global::ProtoBuf.IExtensible
  {
    public Monster() {}
    
    private readonly global::System.Collections.Generic.List<Monster.Item> _items = new global::System.Collections.Generic.List<Monster.Item>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Monster.Item> items
    {
      get { return _items; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Item")]
  public partial class Item : global::ProtoBuf.IExtensible
  {
    public Item() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private int _CreatureID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"CreatureID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int CreatureID
    {
      get { return _CreatureID; }
      set { _CreatureID = value; }
    }
    private int _Camp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Camp
    {
      get { return _Camp; }
      set { _Camp = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private int _Type;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private float _View;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"View", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float View
    {
      get { return _View; }
      set { _View = value; }
    }
    private float _FlyBack;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"FlyBack", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float FlyBack
    {
      get { return _FlyBack; }
      set { _FlyBack = value; }
    }
    private int _HP;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"HP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int HP
    {
      get { return _HP; }
      set { _HP = value; }
    }
    private int _PhysicsAttack;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"PhysicsAttack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PhysicsAttack
    {
      get { return _PhysicsAttack; }
      set { _PhysicsAttack = value; }
    }
    private int _MagicAttack;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"MagicAttack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MagicAttack
    {
      get { return _MagicAttack; }
      set { _MagicAttack = value; }
    }
    private int _PhysicsDefense;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"PhysicsDefense", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PhysicsDefense
    {
      get { return _PhysicsDefense; }
      set { _PhysicsDefense = value; }
    }
    private int _MagicDefense;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"MagicDefense", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MagicDefense
    {
      get { return _MagicDefense; }
      set { _MagicDefense = value; }
    }
    private int _CriticalStrike;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"CriticalStrike", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int CriticalStrike
    {
      get { return _CriticalStrike; }
      set { _CriticalStrike = value; }
    }
    private int _AntiCriticalStrike;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"AntiCriticalStrike", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int AntiCriticalStrike
    {
      get { return _AntiCriticalStrike; }
      set { _AntiCriticalStrike = value; }
    }
    private int _Parry;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"Parry", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Parry
    {
      get { return _Parry; }
      set { _Parry = value; }
    }
    private int _AntiParry;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"AntiParry", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int AntiParry
    {
      get { return _AntiParry; }
      set { _AntiParry = value; }
    }
    private int _Dodge;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"Dodge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Dodge
    {
      get { return _Dodge; }
      set { _Dodge = value; }
    }
    private int _Hit;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"Hit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Hit
    {
      get { return _Hit; }
      set { _Hit = value; }
    }
    private int _Armor;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"Armor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Armor
    {
      get { return _Armor; }
      set { _Armor = value; }
    }
    private int _AntiArmor;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"AntiArmor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int AntiArmor
    {
      get { return _AntiArmor; }
      set { _AntiArmor = value; }
    }
    private int _DamageReduction;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"DamageReduction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int DamageReduction
    {
      get { return _DamageReduction; }
      set { _DamageReduction = value; }
    }
    private int _DamageAdd;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"DamageAdd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int DamageAdd
    {
      get { return _DamageAdd; }
      set { _DamageAdd = value; }
    }
    private int _MoveSpeed;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"MoveSpeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MoveSpeed
    {
      get { return _MoveSpeed; }
      set { _MoveSpeed = value; }
    }
    private int _Dynamic;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"Dynamic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Dynamic
    {
      get { return _Dynamic; }
      set { _Dynamic = value; }
    }
    private int _AI;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"AI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int AI
    {
      get { return _AI; }
      set { _AI = value; }
    }
    private int _PrizeAttenuation;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"PrizeAttenuation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PrizeAttenuation
    {
      get { return _PrizeAttenuation; }
      set { _PrizeAttenuation = value; }
    }
    private int _PrizeID;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"PrizeID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PrizeID
    {
      get { return _PrizeID; }
      set { _PrizeID = value; }
    }
    private int _EXP;
    [global::ProtoBuf.ProtoMember(29, IsRequired = true, Name=@"EXP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int EXP
    {
      get { return _EXP; }
      set { _EXP = value; }
    }
    private int _Money;
    [global::ProtoBuf.ProtoMember(30, IsRequired = true, Name=@"Money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Money
    {
      get { return _Money; }
      set { _Money = value; }
    }
    private string _HeadImg;
    [global::ProtoBuf.ProtoMember(31, IsRequired = true, Name=@"HeadImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string HeadImg
    {
      get { return _HeadImg; }
      set { _HeadImg = value; }
    }
    private bool _ShowHeadLife;
    [global::ProtoBuf.ProtoMember(32, IsRequired = true, Name=@"ShowHeadLife", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool ShowHeadLife
    {
      get { return _ShowHeadLife; }
      set { _ShowHeadLife = value; }
    }
    private int _GeneralSkillID;
    [global::ProtoBuf.ProtoMember(33, IsRequired = true, Name=@"GeneralSkillID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int GeneralSkillID
    {
      get { return _GeneralSkillID; }
      set { _GeneralSkillID = value; }
    }
    private int _AttackType;
    [global::ProtoBuf.ProtoMember(34, IsRequired = true, Name=@"AttackType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int AttackType
    {
      get { return _AttackType; }
      set { _AttackType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Creature")]
  public partial class Creature : global::ProtoBuf.IExtensible
  {
    public Creature() {}
    
    private readonly global::System.Collections.Generic.List<Creature.Item> _items = new global::System.Collections.Generic.List<Creature.Item>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Creature.Item> items
    {
      get { return _items; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Item")]
  public partial class Item : global::ProtoBuf.IExtensible
  {
    public Item() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Prefab;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Prefab", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Prefab
    {
      get { return _Prefab; }
      set { _Prefab = value; }
    }
    private float _ColorR;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ColorR", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ColorR
    {
      get { return _ColorR; }
      set { _ColorR = value; }
    }
    private float _ColorG;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ColorG", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ColorG
    {
      get { return _ColorG; }
      set { _ColorG = value; }
    }
    private float _ColorB;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"ColorB", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ColorB
    {
      get { return _ColorB; }
      set { _ColorB = value; }
    }
    private float _ColorA;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"ColorA", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ColorA
    {
      get { return _ColorA; }
      set { _ColorA = value; }
    }
    private float _Scale;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"Scale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Scale
    {
      get { return _Scale; }
      set { _Scale = value; }
    }
    private float _NameHeight;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"NameHeight", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float NameHeight
    {
      get { return _NameHeight; }
      set { _NameHeight = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterName")]
  public partial class CharacterName : global::ProtoBuf.IExtensible
  {
    public CharacterName() {}
    
    private readonly global::System.Collections.Generic.List<CharacterName.Item> _items = new global::System.Collections.Generic.List<CharacterName.Item>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CharacterName.Item> items
    {
      get { return _items; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Item")]
  public partial class Item : global::ProtoBuf.IExtensible
  {
    public Item() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _country;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"country", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int country
    {
      get { return _country; }
      set { _country = value; }
    }
    private string _lastname;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lastname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string lastname
    {
      get { return _lastname; }
      set { _lastname = value; }
    }
    private string _man;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"man", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string man
    {
      get { return _man; }
      set { _man = value; }
    }
    private string _woman;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"woman", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string woman
    {
      get { return _woman; }
      set { _woman = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillVocation")]
  public partial class SkillVocation : global::ProtoBuf.IExtensible
  {
    public SkillVocation() {}
    
    private readonly global::System.Collections.Generic.List<SkillVocation.Item> _items = new global::System.Collections.Generic.List<SkillVocation.Item>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SkillVocation.Item> items
    {
      get { return _items; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Item")]
  public partial class Item : global::ProtoBuf.IExtensible
  {
    public Item() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _Combo1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Combo1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Combo1
    {
      get { return _Combo1; }
      set { _Combo1 = value; }
    }
    private int _Combo2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Combo2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Combo2
    {
      get { return _Combo2; }
      set { _Combo2 = value; }
    }
    private int _Combo3;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Combo3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Combo3
    {
      get { return _Combo3; }
      set { _Combo3 = value; }
    }
    private int _VocationAttack1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"VocationAttack1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int VocationAttack1
    {
      get { return _VocationAttack1; }
      set { _VocationAttack1 = value; }
    }
    private int _VocationAttack2;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"VocationAttack2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int VocationAttack2
    {
      get { return _VocationAttack2; }
      set { _VocationAttack2 = value; }
    }
    private int _VocationAttack3;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"VocationAttack3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int VocationAttack3
    {
      get { return _VocationAttack3; }
      set { _VocationAttack3 = value; }
    }
    private int _VocationAttack4;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"VocationAttack4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int VocationAttack4
    {
      get { return _VocationAttack4; }
      set { _VocationAttack4 = value; }
    }
    private int _Angry;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"Angry", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Angry
    {
      get { return _Angry; }
      set { _Angry = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Skill")]
  public partial class Skill : global::ProtoBuf.IExtensible
  {
    public Skill() {}
    
    private readonly global::System.Collections.Generic.List<Skill.Item> _items = new global::System.Collections.Generic.List<Skill.Item>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Skill.Item> items
    {
      get { return _items; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Item")]
  public partial class Item : global::ProtoBuf.IExtensible
  {
    public Item() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Tips;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Tips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Tips
    {
      get { return _Tips; }
      set { _Tips = value; }
    }
    private string _Icon;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Icon
    {
      get { return _Icon; }
      set { _Icon = value; }
    }
    private string _FightIcon;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"FightIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string FightIcon
    {
      get { return _FightIcon; }
      set { _FightIcon = value; }
    }
    private int _Target;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Target
    {
      get { return _Target; }
      set { _Target = value; }
    }
    private string _CastAnimation;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"CastAnimation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CastAnimation
    {
      get { return _CastAnimation; }
      set { _CastAnimation = value; }
    }
    private string _AttackAnimation;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"AttackAnimation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AttackAnimation
    {
      get { return _AttackAnimation; }
      set { _AttackAnimation = value; }
    }
    private string _BehitAnimation;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"BehitAnimation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string BehitAnimation
    {
      get { return _BehitAnimation; }
      set { _BehitAnimation = value; }
    }
    private string _CastEffect;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"CastEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CastEffect
    {
      get { return _CastEffect; }
      set { _CastEffect = value; }
    }
    private string _CasetEffectBone;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"CasetEffectBone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CasetEffectBone
    {
      get { return _CasetEffectBone; }
      set { _CasetEffectBone = value; }
    }
    private string _AttackEffect;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"AttackEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AttackEffect
    {
      get { return _AttackEffect; }
      set { _AttackEffect = value; }
    }
    private string _AttackEffectBone;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"AttackEffectBone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AttackEffectBone
    {
      get { return _AttackEffectBone; }
      set { _AttackEffectBone = value; }
    }
    private string _BehitEffect;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"BehitEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string BehitEffect
    {
      get { return _BehitEffect; }
      set { _BehitEffect = value; }
    }
    private string _DieEffect;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"DieEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DieEffect
    {
      get { return _DieEffect; }
      set { _DieEffect = value; }
    }
    private string _DieAnimation;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"DieAnimation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DieAnimation
    {
      get { return _DieAnimation; }
      set { _DieAnimation = value; }
    }
    private int _AttackSound;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"AttackSound", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int AttackSound
    {
      get { return _AttackSound; }
      set { _AttackSound = value; }
    }
    private string _HitSound;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"HitSound", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string HitSound
    {
      get { return _HitSound; }
      set { _HitSound = value; }
    }
    private int _Hatred;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"Hatred", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Hatred
    {
      get { return _Hatred; }
      set { _Hatred = value; }
    }
    private int _DamageType;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"DamageType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int DamageType
    {
      get { return _DamageType; }
      set { _DamageType = value; }
    }
    private float _DamageParameter1;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"DamageParameter1", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DamageParameter1
    {
      get { return _DamageParameter1; }
      set { _DamageParameter1 = value; }
    }
    private float _DamageParameter2;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"DamageParameter2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DamageParameter2
    {
      get { return _DamageParameter2; }
      set { _DamageParameter2 = value; }
    }
    private float _DamageParameter3;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"DamageParameter3", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DamageParameter3
    {
      get { return _DamageParameter3; }
      set { _DamageParameter3 = value; }
    }
    private float _DamageDistance;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"DamageDistance", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DamageDistance
    {
      get { return _DamageDistance; }
      set { _DamageDistance = value; }
    }
    private int _CoolDownTime;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"CoolDownTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int CoolDownTime
    {
      get { return _CoolDownTime; }
      set { _CoolDownTime = value; }
    }
    private int _SingTime;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"SingTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SingTime
    {
      get { return _SingTime; }
      set { _SingTime = value; }
    }
    private int _IsDamagedOnlyOnce;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"IsDamagedOnlyOnce", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int IsDamagedOnlyOnce
    {
      get { return _IsDamagedOnlyOnce; }
      set { _IsDamagedOnlyOnce = value; }
    }
    private int _DamageInterval;
    [global::ProtoBuf.ProtoMember(29, IsRequired = true, Name=@"DamageInterval", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int DamageInterval
    {
      get { return _DamageInterval; }
      set { _DamageInterval = value; }
    }
    private int _ActiveHardStraightTime;
    [global::ProtoBuf.ProtoMember(30, IsRequired = true, Name=@"ActiveHardStraightTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ActiveHardStraightTime
    {
      get { return _ActiveHardStraightTime; }
      set { _ActiveHardStraightTime = value; }
    }
    private int _PassiveHardStraightTime;
    [global::ProtoBuf.ProtoMember(31, IsRequired = true, Name=@"PassiveHardStraightTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PassiveHardStraightTime
    {
      get { return _PassiveHardStraightTime; }
      set { _PassiveHardStraightTime = value; }
    }
    private int _PushDistance;
    [global::ProtoBuf.ProtoMember(32, IsRequired = true, Name=@"PushDistance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PushDistance
    {
      get { return _PushDistance; }
      set { _PushDistance = value; }
    }
    private int _BlowFlyDistance;
    [global::ProtoBuf.ProtoMember(33, IsRequired = true, Name=@"BlowFlyDistance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int BlowFlyDistance
    {
      get { return _BlowFlyDistance; }
      set { _BlowFlyDistance = value; }
    }
    private float _BlowFlyAngle;
    [global::ProtoBuf.ProtoMember(34, IsRequired = true, Name=@"BlowFlyAngle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float BlowFlyAngle
    {
      get { return _BlowFlyAngle; }
      set { _BlowFlyAngle = value; }
    }
    private int _FloatingTime;
    [global::ProtoBuf.ProtoMember(35, IsRequired = true, Name=@"FloatingTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int FloatingTime
    {
      get { return _FloatingTime; }
      set { _FloatingTime = value; }
    }
    private float _FloatingHeight;
    [global::ProtoBuf.ProtoMember(36, IsRequired = true, Name=@"FloatingHeight", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float FloatingHeight
    {
      get { return _FloatingHeight; }
      set { _FloatingHeight = value; }
    }
    private int _AssaultDistance;
    [global::ProtoBuf.ProtoMember(37, IsRequired = true, Name=@"AssaultDistance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int AssaultDistance
    {
      get { return _AssaultDistance; }
      set { _AssaultDistance = value; }
    }
    private int _Buff1;
    [global::ProtoBuf.ProtoMember(38, IsRequired = true, Name=@"Buff1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Buff1
    {
      get { return _Buff1; }
      set { _Buff1 = value; }
    }
    private float _BuffProbability1;
    [global::ProtoBuf.ProtoMember(39, IsRequired = true, Name=@"BuffProbability1", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float BuffProbability1
    {
      get { return _BuffProbability1; }
      set { _BuffProbability1 = value; }
    }
    private int _Buff2;
    [global::ProtoBuf.ProtoMember(40, IsRequired = true, Name=@"Buff2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Buff2
    {
      get { return _Buff2; }
      set { _Buff2 = value; }
    }
    private float _BuffProbability2;
    [global::ProtoBuf.ProtoMember(41, IsRequired = true, Name=@"BuffProbability2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float BuffProbability2
    {
      get { return _BuffProbability2; }
      set { _BuffProbability2 = value; }
    }
    private int _Buff3;
    [global::ProtoBuf.ProtoMember(42, IsRequired = true, Name=@"Buff3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Buff3
    {
      get { return _Buff3; }
      set { _Buff3 = value; }
    }
    private float _BuffProbability3;
    [global::ProtoBuf.ProtoMember(43, IsRequired = true, Name=@"BuffProbability3", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float BuffProbability3
    {
      get { return _BuffProbability3; }
      set { _BuffProbability3 = value; }
    }
    private int _AttackPoint;
    [global::ProtoBuf.ProtoMember(44, IsRequired = true, Name=@"AttackPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int AttackPoint
    {
      get { return _AttackPoint; }
      set { _AttackPoint = value; }
    }
    private int _AttackPercentage;
    [global::ProtoBuf.ProtoMember(45, IsRequired = true, Name=@"AttackPercentage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int AttackPercentage
    {
      get { return _AttackPercentage; }
      set { _AttackPercentage = value; }
    }
    private int _IgnoreDefensePoint;
    [global::ProtoBuf.ProtoMember(46, IsRequired = true, Name=@"IgnoreDefensePoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int IgnoreDefensePoint
    {
      get { return _IgnoreDefensePoint; }
      set { _IgnoreDefensePoint = value; }
    }
    private int _IgnoreDefensePercentage;
    [global::ProtoBuf.ProtoMember(47, IsRequired = true, Name=@"IgnoreDefensePercentage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int IgnoreDefensePercentage
    {
      get { return _IgnoreDefensePercentage; }
      set { _IgnoreDefensePercentage = value; }
    }
    private int _DamagePoint;
    [global::ProtoBuf.ProtoMember(48, IsRequired = true, Name=@"DamagePoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int DamagePoint
    {
      get { return _DamagePoint; }
      set { _DamagePoint = value; }
    }
    private int _DamagePercentage;
    [global::ProtoBuf.ProtoMember(49, IsRequired = true, Name=@"DamagePercentage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int DamagePercentage
    {
      get { return _DamagePercentage; }
      set { _DamagePercentage = value; }
    }
    private int _BreakPoint;
    [global::ProtoBuf.ProtoMember(50, IsRequired = true, Name=@"BreakPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int BreakPoint
    {
      get { return _BreakPoint; }
      set { _BreakPoint = value; }
    }
    private int _CriticalPoint;
    [global::ProtoBuf.ProtoMember(51, IsRequired = true, Name=@"CriticalPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int CriticalPoint
    {
      get { return _CriticalPoint; }
      set { _CriticalPoint = value; }
    }
    private int _Hit;
    [global::ProtoBuf.ProtoMember(52, IsRequired = true, Name=@"Hit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Hit
    {
      get { return _Hit; }
      set { _Hit = value; }
    }
    private int _Pierce;
    [global::ProtoBuf.ProtoMember(53, IsRequired = true, Name=@"Pierce", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Pierce
    {
      get { return _Pierce; }
      set { _Pierce = value; }
    }
    private int _SkillType;
    [global::ProtoBuf.ProtoMember(54, IsRequired = true, Name=@"SkillType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SkillType
    {
      get { return _SkillType; }
      set { _SkillType = value; }
    }
    private int _PhysicsOrMagic;
    [global::ProtoBuf.ProtoMember(55, IsRequired = true, Name=@"PhysicsOrMagic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PhysicsOrMagic
    {
      get { return _PhysicsOrMagic; }
      set { _PhysicsOrMagic = value; }
    }
    private int _Shake;
    [global::ProtoBuf.ProtoMember(56, IsRequired = true, Name=@"Shake", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Shake
    {
      get { return _Shake; }
      set { _Shake = value; }
    }
    private bool _StopByRun;
    [global::ProtoBuf.ProtoMember(57, IsRequired = true, Name=@"StopByRun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool StopByRun
    {
      get { return _StopByRun; }
      set { _StopByRun = value; }
    }
    private bool _CanMove;
    [global::ProtoBuf.ProtoMember(58, IsRequired = true, Name=@"CanMove", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool CanMove
    {
      get { return _CanMove; }
      set { _CanMove = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WorldMap")]
  public partial class WorldMap : global::ProtoBuf.IExtensible
  {
    public WorldMap() {}
    
    private readonly global::System.Collections.Generic.List<WorldMap.Item> _items = new global::System.Collections.Generic.List<WorldMap.Item>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<WorldMap.Item> items
    {
      get { return _items; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Item")]
  public partial class Item : global::ProtoBuf.IExtensible
  {
    public Item() {}
    
    private int _MapID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MapID
    {
      get { return _MapID; }
      set { _MapID = value; }
    }
    private string _InWayPoint1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"InWayPoint1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string InWayPoint1
    {
      get { return _InWayPoint1; }
      set { _InWayPoint1 = value; }
    }
    private int _OutWayMapID1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"OutWayMapID1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OutWayMapID1
    {
      get { return _OutWayMapID1; }
      set { _OutWayMapID1 = value; }
    }
    private string _OutWayPoint1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"OutWayPoint1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string OutWayPoint1
    {
      get { return _OutWayPoint1; }
      set { _OutWayPoint1 = value; }
    }
    private string _InWayPoint2;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"InWayPoint2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string InWayPoint2
    {
      get { return _InWayPoint2; }
      set { _InWayPoint2 = value; }
    }
    private int _OutWayMapID2;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"OutWayMapID2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OutWayMapID2
    {
      get { return _OutWayMapID2; }
      set { _OutWayMapID2 = value; }
    }
    private string _OutWayPoint2;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"OutWayPoint2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string OutWayPoint2
    {
      get { return _OutWayPoint2; }
      set { _OutWayPoint2 = value; }
    }
    private string _InWayPoint3;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"InWayPoint3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string InWayPoint3
    {
      get { return _InWayPoint3; }
      set { _InWayPoint3 = value; }
    }
    private int _OutWayMapID3;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"OutWayMapID3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OutWayMapID3
    {
      get { return _OutWayMapID3; }
      set { _OutWayMapID3 = value; }
    }
    private string _OutWayPoint3;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"OutWayPoint3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string OutWayPoint3
    {
      get { return _OutWayPoint3; }
      set { _OutWayPoint3 = value; }
    }
    private string _InWayPoint4;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"InWayPoint4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string InWayPoint4
    {
      get { return _InWayPoint4; }
      set { _InWayPoint4 = value; }
    }
    private int _OutWayMapID4;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"OutWayMapID4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OutWayMapID4
    {
      get { return _OutWayMapID4; }
      set { _OutWayMapID4 = value; }
    }
    private string _OutWayPoint4;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"OutWayPoint4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string OutWayPoint4
    {
      get { return _OutWayPoint4; }
      set { _OutWayPoint4 = value; }
    }
    private int _NPCID;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"NPCID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int NPCID
    {
      get { return _NPCID; }
      set { _NPCID = value; }
    }
    private int _OutNPCMapID1;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"OutNPCMapID1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OutNPCMapID1
    {
      get { return _OutNPCMapID1; }
      set { _OutNPCMapID1 = value; }
    }
    private string _OutNPCPoint1;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"OutNPCPoint1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string OutNPCPoint1
    {
      get { return _OutNPCPoint1; }
      set { _OutNPCPoint1 = value; }
    }
    private int _OutNPCMapID2;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"OutNPCMapID2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OutNPCMapID2
    {
      get { return _OutNPCMapID2; }
      set { _OutNPCMapID2 = value; }
    }
    private string _OutNPCPoint2;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"OutNPCPoint2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string OutNPCPoint2
    {
      get { return _OutNPCPoint2; }
      set { _OutNPCPoint2 = value; }
    }
    private int _OutNPCMapID3;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"OutNPCMapID3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OutNPCMapID3
    {
      get { return _OutNPCMapID3; }
      set { _OutNPCMapID3 = value; }
    }
    private string _OutNPCPoint3;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"OutNPCPoint3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string OutNPCPoint3
    {
      get { return _OutNPCPoint3; }
      set { _OutNPCPoint3 = value; }
    }
    private int _OutNPCMapID4;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"OutNPCMapID4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OutNPCMapID4
    {
      get { return _OutNPCMapID4; }
      set { _OutNPCMapID4 = value; }
    }
    private string _OutNPCPoint4;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"OutNPCPoint4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string OutNPCPoint4
    {
      get { return _OutNPCPoint4; }
      set { _OutNPCPoint4 = value; }
    }
    private int _OutNPCMapID5;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"OutNPCMapID5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OutNPCMapID5
    {
      get { return _OutNPCMapID5; }
      set { _OutNPCMapID5 = value; }
    }
    private string _OutNPCPoint5;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"OutNPCPoint5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string OutNPCPoint5
    {
      get { return _OutNPCPoint5; }
      set { _OutNPCPoint5 = value; }
    }
    private int _OutNPCMapID6;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"OutNPCMapID6", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OutNPCMapID6
    {
      get { return _OutNPCMapID6; }
      set { _OutNPCMapID6 = value; }
    }
    private string _OutNPCPoint6;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"OutNPCPoint6", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string OutNPCPoint6
    {
      get { return _OutNPCPoint6; }
      set { _OutNPCPoint6 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillAttackFrameMap")]
  public partial class SkillAttackFrameMap : global::ProtoBuf.IExtensible
  {
    public SkillAttackFrameMap() {}
    
    private readonly global::System.Collections.Generic.List<SkillAttackFrameMap.Item> _items = new global::System.Collections.Generic.List<SkillAttackFrameMap.Item>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SkillAttackFrameMap.Item> items
    {
      get { return _items; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Item")]
  public partial class Item : global::ProtoBuf.IExtensible
  {
    public Item() {}
    
    private string _AnimationName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"AnimationName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AnimationName
    {
      get { return _AnimationName; }
      set { _AnimationName = value; }
    }
    private float _Frame1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Frame1", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Frame1
    {
      get { return _Frame1; }
      set { _Frame1 = value; }
    }
    private float _Frame2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Frame2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Frame2
    {
      get { return _Frame2; }
      set { _Frame2 = value; }
    }
    private float _Frame3;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Frame3", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Frame3
    {
      get { return _Frame3; }
      set { _Frame3 = value; }
    }
    private float _Frame4;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Frame4", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Frame4
    {
      get { return _Frame4; }
      set { _Frame4 = value; }
    }
    private float _Frame5;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Frame5", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Frame5
    {
      get { return _Frame5; }
      set { _Frame5 = value; }
    }
    private string _Tips;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Tips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Tips
    {
      get { return _Tips; }
      set { _Tips = value; }
    }
    private float _Speed;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"Speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Speed
    {
      get { return _Speed; }
      set { _Speed = value; }
    }
    private float _ShakeFrame1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"ShakeFrame1", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ShakeFrame1
    {
      get { return _ShakeFrame1; }
      set { _ShakeFrame1 = value; }
    }
    private float _ShakeFrame2;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"ShakeFrame2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ShakeFrame2
    {
      get { return _ShakeFrame2; }
      set { _ShakeFrame2 = value; }
    }
    private float _ShakeFrame3;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"ShakeFrame3", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ShakeFrame3
    {
      get { return _ShakeFrame3; }
      set { _ShakeFrame3 = value; }
    }
    private float _ShakeFrame4;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"ShakeFrame4", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ShakeFrame4
    {
      get { return _ShakeFrame4; }
      set { _ShakeFrame4 = value; }
    }
    private float _ShakeFrame5;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"ShakeFrame5", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ShakeFrame5
    {
      get { return _ShakeFrame5; }
      set { _ShakeFrame5 = value; }
    }
    private float _ShakeRange1;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"ShakeRange1", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ShakeRange1
    {
      get { return _ShakeRange1; }
      set { _ShakeRange1 = value; }
    }
    private float _ShakeRange2;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"ShakeRange2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ShakeRange2
    {
      get { return _ShakeRange2; }
      set { _ShakeRange2 = value; }
    }
    private float _ShakeRange3;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"ShakeRange3", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ShakeRange3
    {
      get { return _ShakeRange3; }
      set { _ShakeRange3 = value; }
    }
    private float _ShakeRange4;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"ShakeRange4", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ShakeRange4
    {
      get { return _ShakeRange4; }
      set { _ShakeRange4 = value; }
    }
    private float _ShakeRange5;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"ShakeRange5", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ShakeRange5
    {
      get { return _ShakeRange5; }
      set { _ShakeRange5 = value; }
    }
    private float _ShakeTime1;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"ShakeTime1", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ShakeTime1
    {
      get { return _ShakeTime1; }
      set { _ShakeTime1 = value; }
    }
    private float _ShakeTime2;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"ShakeTime2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ShakeTime2
    {
      get { return _ShakeTime2; }
      set { _ShakeTime2 = value; }
    }
    private float _ShakeTime3;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"ShakeTime3", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ShakeTime3
    {
      get { return _ShakeTime3; }
      set { _ShakeTime3 = value; }
    }
    private float _ShakeTime4;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"ShakeTime4", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ShakeTime4
    {
      get { return _ShakeTime4; }
      set { _ShakeTime4 = value; }
    }
    private float _ShakeTime5;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"ShakeTime5", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ShakeTime5
    {
      get { return _ShakeTime5; }
      set { _ShakeTime5 = value; }
    }
    private float _SoundFrame1;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"SoundFrame1", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float SoundFrame1
    {
      get { return _SoundFrame1; }
      set { _SoundFrame1 = value; }
    }
    private string _SoundFile1;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"SoundFile1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SoundFile1
    {
      get { return _SoundFile1; }
      set { _SoundFile1 = value; }
    }
    private float _SoundFrame2;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"SoundFrame2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float SoundFrame2
    {
      get { return _SoundFrame2; }
      set { _SoundFrame2 = value; }
    }
    private string _SoundFile2;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"SoundFile2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SoundFile2
    {
      get { return _SoundFile2; }
      set { _SoundFile2 = value; }
    }
    private float _SoundFrame3;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"SoundFrame3", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float SoundFrame3
    {
      get { return _SoundFrame3; }
      set { _SoundFrame3 = value; }
    }
    private string _SoundFile3;
    [global::ProtoBuf.ProtoMember(29, IsRequired = true, Name=@"SoundFile3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SoundFile3
    {
      get { return _SoundFile3; }
      set { _SoundFile3 = value; }
    }
    private float _SoundFrame4;
    [global::ProtoBuf.ProtoMember(30, IsRequired = true, Name=@"SoundFrame4", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float SoundFrame4
    {
      get { return _SoundFrame4; }
      set { _SoundFrame4 = value; }
    }
    private string _SoundFile4;
    [global::ProtoBuf.ProtoMember(31, IsRequired = true, Name=@"SoundFile4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SoundFile4
    {
      get { return _SoundFile4; }
      set { _SoundFile4 = value; }
    }
    private float _SoundFrame5;
    [global::ProtoBuf.ProtoMember(32, IsRequired = true, Name=@"SoundFrame5", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float SoundFrame5
    {
      get { return _SoundFrame5; }
      set { _SoundFrame5 = value; }
    }
    private string _SoundFile5;
    [global::ProtoBuf.ProtoMember(33, IsRequired = true, Name=@"SoundFile5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SoundFile5
    {
      get { return _SoundFile5; }
      set { _SoundFile5 = value; }
    }
    private float _DieFrame;
    [global::ProtoBuf.ProtoMember(34, IsRequired = true, Name=@"DieFrame", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DieFrame
    {
      get { return _DieFrame; }
      set { _DieFrame = value; }
    }
    private string _DieSoundFile;
    [global::ProtoBuf.ProtoMember(35, IsRequired = true, Name=@"DieSoundFile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DieSoundFile
    {
      get { return _DieSoundFile; }
      set { _DieSoundFile = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapNavigate")]
  public partial class MapNavigate : global::ProtoBuf.IExtensible
  {
    public MapNavigate() {}
    
    private readonly global::System.Collections.Generic.List<MapNavigate.Item> _items = new global::System.Collections.Generic.List<MapNavigate.Item>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapNavigate.Item> items
    {
      get { return _items; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Item")]
  public partial class Item : global::ProtoBuf.IExtensible
  {
    public Item() {}
    
    private int _Mapid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Mapid
    {
      get { return _Mapid; }
      set { _Mapid = value; }
    }
    private string _MapName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"MapName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string MapName
    {
      get { return _MapName; }
      set { _MapName = value; }
    }
    private int _DesMap;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"DesMap", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int DesMap
    {
      get { return _DesMap; }
      set { _DesMap = value; }
    }
    private int _Via1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Via1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Via1
    {
      get { return _Via1; }
      set { _Via1 = value; }
    }
    private int _Via2;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Via2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Via2
    {
      get { return _Via2; }
      set { _Via2 = value; }
    }
    private int _Via3;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Via3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Via3
    {
      get { return _Via3; }
      set { _Via3 = value; }
    }
    private int _Via4;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Via4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Via4
    {
      get { return _Via4; }
      set { _Via4 = value; }
    }
    private int _Via5;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"Via5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Via5
    {
      get { return _Via5; }
      set { _Via5 = value; }
    }
    private int _Via6;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"Via6", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Via6
    {
      get { return _Via6; }
      set { _Via6 = value; }
    }
    private int _Via7;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"Via7", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Via7
    {
      get { return _Via7; }
      set { _Via7 = value; }
    }
    private int _Via8;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"Via8", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Via8
    {
      get { return _Via8; }
      set { _Via8 = value; }
    }
    private int _Via9;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"Via9", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Via9
    {
      get { return _Via9; }
      set { _Via9 = value; }
    }
    private int _Via10;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"Via10", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Via10
    {
      get { return _Via10; }
      set { _Via10 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}